services:
  web:
    build:
      context: .
    image: workstation-web:1.0 # 이미지 태그 
    container_name: workstation-web # 컨테이너 이름
    ports:
      - "8080:80"
    volumes:
      - popyou:/usr/share/nginx/html/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    image: workstation-backend:1.0
    container_name: workstation-backend
    expose:
      - "8000"

volumes:
  popyou:

